"""empty message

Revision ID: 7c1a0a44bb96
Revises: 6971773c8c5f
Create Date: 2021-02-04 21:06:17.772578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1a0a44bb96'
down_revision = '6971773c8c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('group_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_member',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_constraint('subtasks_task_id_fkey', 'subtasks', type_='foreignkey')
    op.create_foreign_key(None, 'subtasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.create_foreign_key('subtasks_task_id_fkey', 'subtasks', 'tasks', ['task_id'], ['id'])
    op.drop_table('group_member')
    op.drop_table('group')
    # ### end Alembic commands ###
