"""Updated Task and Group table and CRUD

Revision ID: 8b97b2ed85f7
Revises: e29084162323
Create Date: 2021-02-16 13:58:24.695591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b97b2ed85f7'
down_revision = 'e29084162323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'group_id')
    op.drop_column('groups', 'is_public')
    # ### end Alembic commands ###
