"""Update Group Member Fkeys.

Revision ID: e29084162323
Revises: 2568c1256eff
Create Date: 2021-02-15 13:16:54.087800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29084162323'
down_revision = '2568c1256eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_member_group_id_fkey', 'group_member', type_='foreignkey')
    op.drop_constraint('group_member_user_id_fkey', 'group_member', type_='foreignkey')
    op.create_foreign_key(None, 'group_member', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_member', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_member', type_='foreignkey')
    op.drop_constraint(None, 'group_member', type_='foreignkey')
    op.create_foreign_key('group_member_user_id_fkey', 'group_member', 'users', ['user_id'], ['id'])
    op.create_foreign_key('group_member_group_id_fkey', 'group_member', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
