"""Add AssignedTo Table

Revision ID: 365c623b1e03
Revises: 839c7fc114fd
Create Date: 2021-06-20 15:48:16.496822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365c623b1e03'
down_revision = '839c7fc114fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER_ASSIGNED_TO_SUBTASK',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subtask_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subtask_id')
    )
    op.alter_column('group_member', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_member', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_member', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('group_member', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('USER_ASSIGNED_TO_SUBTASK')
    # ### end Alembic commands ###
