"""Simplify Tables

Revision ID: e823be1ebca7
Revises: 69f2a2cbaf82
Create Date: 2021-06-29 15:38:59.857064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e823be1ebca7'
down_revision = '69f2a2cbaf82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('subtasks', 'group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subtasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('subtasks', 'index')
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tasks', 'index')
    op.alter_column('users', 'emailaddress',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'phonenumber',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'phonenumber',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'emailaddress',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.add_column('tasks', sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('subtasks', sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('subtasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subtasks', 'group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subtasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
